Update the links to our code of conduct
fastruby/dash pull request #104
Opened 2021-07-23 20:22 UTC by cleicar

Description:

This closes #87.

I will abide by the code of conduct.

2021-07-26 13:33 UTC, arielj requested changes
Hey @cleicar I added one comment to make it easier to maintain in case it ever changes name/org/branch, using relative paths instead

https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/creating-a-repository-on-github/about-readmes#relative-links-and-image-paths-in-readme-files

2021-07-26 13:33 UTC, arielj commented on .github/ISSUE_TEMPLATE/bug_report.md
> +**I will abide by the [code of conduct] (https://github.com/fastruby/dash/blob/main/CODE_OF_CONDUCT.md)**
I think we can do `**I will abide by the [code of conduct](./CODE_OF_CONDUCT.md)**` so it's easier to maintain. The link href works relative to the current file's directory https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/creating-a-repository-on-github/about-readmes#relative-links-and-image-paths-in-readme-files

2021-07-26 13:33 UTC, arielj commented on README.md
> +  Everyone interacting in the Dash project’s codebases, issue trackers, chat rooms and mailing lists is expected to follow the [code of conduct](https://github.com/fastruby/dash/blob/main/CODE_OF_CON
similar here in the README, but without the `./` since it's in the same folder

2021-07-26 13:34 UTC, arielj commented on README.md
> +[![CircleCI](https://circleci.com/gh/ombulabs/dash/tree/master.svg?style=svg&circle-token=aa41e55b03a167988f14667d78d1d7c0183f2656)](https://circleci.com/gh/ombulabs/dash/tree/master)  [![Contributor
similar here in the README, but without the `./` since it's in the same folder

2021-07-26 13:34 UTC, arielj commented on README.md
> +  Everyone interacting in the Dash project’s codebases, issue trackers, chat rooms and mailing lists is expected to follow the [code of conduct](https://github.com/fastruby/dash/blob/main/CODE_OF_CON
this was ok without the absolute url

2021-07-26 13:38 UTC, arielj commented on .github/ISSUE_TEMPLATE/bug_report.md
> +**I will abide by the [code of conduct] (https://github.com/fastruby/dash/blob/main/CODE_OF_CONDUCT.md)**
also, I think there's a space between `[code of conduct]` and the `(...)` breaking the link formatting (it was not introduced on this PR, it happens on main too, but maybe it's worth to fix it here)

2021-07-26 14:03 UTC, arielj commented on .github/ISSUE_TEMPLATE/bug_report.md
> +**I will abide by the [code of conduct] (https://github.com/fastruby/dash/blob/main/CODE_OF_CONDUCT.md)**
UPDATE on this: just tested and the way to use relative paths on a PR is `[code of conduct](../blob/main/CODE_OF_CONDUCT.md)`

I guess we still need the `main` part on the link

2021-07-30 21:40 UTC, cleicar commented
Thanks for your feedback @arielj, make sense!

But I'm finding hard to test it here and make sure that it works.

2021-08-03 12:21 UTC, arielj approved these changes
You can test the PR template change by adding that link here on this PR for the PR template

Also, I used that link version on this issue https://github.com/fastruby/dash/issues/108 and the link works for issue templates too.

It looks good to me

2021-08-11 03:42 UTC, merged