Feature/change pivotal button place
fastruby/dash pull request #110
Opened 2021-07-30 18:13 UTC by cleicar

**Description:**

This changes the location of the `Edit Pivotal token` button because ir make more sense to be long side with the `Sign out` button.

**Screenshots**

<img width="1439" alt="Screen Shot 2021-07-30 at 15 11 02" src="https://user-images.githubusercontent.com/11785031/127694839-b30e0b5d-0497-4cb8-8640-91588d60238a.png">

2021-08-03 12:17 UTC, arielj requested changes
Hey @cleicar the changes look good, but there are some extra changes from the other PR changing the templates, can you rever those changes?

2021-08-11 03:43 UTC, bronzdoc commented
@cleicar can you fix the merge conflicts and Address Ariel's comments? thanks!

2021-08-30 23:46 UTC, cleicar commented
@arielj @bronzdoc thanks! I fixed the conflicts :)

2021-09-10 16:03 UTC, lubc approved these changes

2021-09-10 16:04 UTC, merged