Feature/edit pivotal token
fastruby/dash pull request #40
Opened 2020-10-11 04:04 UTC by etagwerker

Hey @arielj, 

This PR fixes #20 with a set of changes to allow you to clear or update your Pivotal Tracker API token. 

I added a new button to the menu: 

![Screen Shot 2020-10-10 at 11 37 18 PM](https://user-images.githubusercontent.com/17584/95670049-0b9e9500-0b55-11eb-8247-bff7be66251c.png)

This takes you to the page where you can edit your token. I also added a validation to make sure that users submit a 32-char API token.

When they don't, they will see this error message: 

![Screen Shot 2020-10-10 at 11 56 41 PM](https://user-images.githubusercontent.com/17584/95670055-1c4f0b00-0b55-11eb-87b7-e738f1fe77db.png)

The validation allows for blank or nil values, so you can easily clear your existing token if you need to.

Please check it out and let me know what you think.

Thanks!

2020-10-13 12:54 UTC, arielj requested changes
Looks good! just added some comments on variables and a method name change.

2020-10-13 12:54 UTC, arielj commented on app/helpers/pivotal_helper.rb
> +  def form_button
can we name this differently? `form_button` sounds like it renders a generic button tag, maybe `token_form_button_text`?

2020-10-13 12:54 UTC, arielj commented on app/views/pivotal/_form.html.erb
> +  <%= form_with model: @user, url: pivotal_path, local: true do |f| %>
I think it would be better to use `current_user` here instead of `@user` (and we can remove the `set_user` before action in the controller)

2020-10-13 12:54 UTC, arielj commented on app/views/pivotal/_form.html.erb
> +    <%= f.text_field :pivotal_token, value: current_user.pivotal_token %>
This `value: ...` shouldn't be needed, it should take the value from the model

2020-10-13 16:07 UTC, etagwerker commented
@arielj All done addressing your comments! Let me know if you find anything else. ;)

2020-10-13 16:12 UTC, arielj approved these changes
Looks good!

2020-10-13 16:49 UTC, etagwerker commented
@FionaDL @ABizzinotto could one of you test this in staging?

2020-10-15 14:54 UTC, arielj commented
Tried removing my pivotal token, then when pressing `sync` it asked me for a new token, put the new one and it's properly updated :+1:

2020-10-15 14:54 UTC, merged