Add opened by you pull requests to the index page
fastruby/dash pull request #42
Opened 2020-10-19 03:42 UTC by FionaDL

Hello, this PR addresses part of issue #16 , I decided only to address seeing PR's that you have opened, and not issues, because I thought the issues could become numerous, and also date quite far back. 

I reorganized the titles for the tables a bit to make this more organized. Let me know what you think:

**Screenshots**
Before:
![Screen Shot 2020-10-18 at 11 38 48 PM](https://user-images.githubusercontent.com/28625558/96399121-97d73a80-119b-11eb-8fd0-6ecd02c83a26.png)

After:
![Screen Shot 2020-10-18 at 11 38 24 PM](https://user-images.githubusercontent.com/28625558/96399128-9c9bee80-119b-11eb-83a6-ee080352d9f0.png)

2020-10-27 19:16 UTC, rdormer approved these changes

2020-10-27 20:45 UTC, arielj requested changes
hey, added some comments! the most important is the `select` call, the rest are not strictly necessary

2020-10-27 20:45 UTC, arielj commented on app/models/user.rb
> +    PullRequest.select{ |pr| pr.author.downcase == self.name.downcase}
Maybe we can translate this into an association? I think now it's fetching all the PRs from the database to compare.

2020-10-27 20:45 UTC, arielj commented on app/views/todos/index.html.erb
> +      <table class="table">
maybe we can move this table into a partial an reuse it also for the `@my_pulls` list, I think it's the same table

2020-10-27 20:45 UTC, arielj commented on db/migrate/20201012013526_add_author_to_pull_request.rb
> +    add_column :pull_requests, :author, :string
maybe this can be called `author_name`? `author` alone can mean an object, an id, a name

2020-11-23 03:12 UTC, FionaDL commented
@arielj I think I have addressed everything. Let me know what you think.

2020-11-24 12:29 UTC, arielj approved these changes

2020-11-24 15:15 UTC, arielj commented on app/views/todos/_github_resource.html.erb
> +        <tr class="table__row table__row--head <%= queue_type %>">
```suggestion
        <tr class="table__row <%= queue_type %>">
```

2020-12-01 21:05 UTC, etagwerker commented
@FionaDL Looks good, thanks! 💯

2020-12-01 21:05 UTC, merged