Make sure the displayed PRs are unic
fastruby/dash pull request #62
Opened 2021-01-29 11:58 UTC by cleicar

This will address issue: #59

2021-01-29 18:07 UTC, FionaDL approved these changes
@cleicar looks good to me.

2021-01-29 18:09 UTC, bronzdoc requested changes
Looks good with a test 👍

2021-01-29 18:09 UTC, bronzdoc commented on app/models/user.rb
> -
can you remove this whitespace?

2021-01-29 18:09 UTC, bronzdoc commented on app/models/user.rb
> -
Can you remove this whitespace?

2021-02-02 01:08 UTC, cleicar commented
Thanks for your review @bronzdoc. I just pushed the changes.

2021-02-02 16:06 UTC, bronzdoc commented
Thanks @cleicar! This change needs a test and we good to go 💪

2021-02-02 23:11 UTC, cleicar commented
@bronzdoc done!

2021-02-03 18:09 UTC, bronzdoc approved these changes
@ABizzinotto this is ready for QA

2021-02-03 22:59 UTC, ABizzinotto commented
@cleicar good to merge!

2021-02-03 23:02 UTC, merged